services:
  db:
    user: "0:0"
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    image: ${PREFECT_IMAGE}
    restart: always
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=${SERVER_PORT}
      - PREFECT_API_URL=http://${SERVER_IP}:${SERVER_PORT}/api
      - PREFECT_SERVER_ANALYTICS_ENABLED=false
      # Чтобы UI был доступен снаружи:
      - PREFECT_UI_URL=http://${SERVER_IP}:${SERVER_PORT}/api
    volumes:
      - ${SERVER_LOGS_PATH}:/logs
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: prefect server start
    depends_on:
      db:
        condition: service_healthy
